services:
  # Contenedor de Base de Datos
  db:
    image: mysql:8.0
    container_name: app_mysql
    restart: always
    environment:
      MYSQL_DATABASE: julian_db
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: julian
      MYSQL_PASSWORD: 12345
    volumes:
      - mysql_data:/var/lib/mysql
      - ./julian_db.sql:/docker-entrypoint-initdb.d/julian_db.sql
    networks:
      - web-network

  # Contenedor de Aplicación
  app:
    build: .
    container_name: app_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html # Sincroniza toda tu carpeta actual
    depends_on:
      - db
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  mysql_data: